<script lang="ts">
  import type { DrillOperation, ImportSummary, StockDefinition, StockMode, WorkCoordinateSystem } from './types';
  import { validateDrillOperation } from './drillGcode';
  export let summary:ImportSummary;export let operation:DrillOperation;export let stock:StockDefinition;export let stockMode:StockMode;export let wcs:WorkCoordinateSystem;
  $: validation=validateDrillOperation(summary,operation);
  $: warnings=[...validation.warnings,...(stockMode==='none'?['Kein Rohling definiert: Materialgrenzen können nur eingeschränkt geprüft werden.']:[]),...(stockMode!=='none'&&operation.totalDepthMm>stock.thickness?[`Bohrtiefe ${operation.totalDepthMm.toFixed(3)} mm überschreitet die Rohlingdicke ${stock.thickness.toFixed(3)} mm.`]:[])];
  $: errors=[...validation.errors,...(wcs.z!=='top'?['WCS Unterseite ist für Bohren in Gate 9B noch nicht freigegeben.']:[])];
  $: overall=errors.length?'fail':warnings.length?'warn':'pass';
  $: layerText=operation.selectionMode==='layer'?(operation.layerName??'keine Ebene'):'Einzelauswahl';
</script>
<p class="eyebrow">05 · Prüfen</p><h2>Bohren</h2>
<div class="release" class:pass={overall==='pass'} class:warn={overall==='warn'} class:fail={overall==='fail'}><strong>{overall.toUpperCase()}</strong><span>{overall==='pass'?'Bohrung ist für Gate 9B freigegeben.':overall==='warn'?'Bohrung ist freigabefähig, enthält aber Hinweise.':'Bohrung ist noch nicht freigegeben.'}</span></div>
<div class="facts"><span>{validation.holeCount} Bohrposition{validation.holeCount===1?'':'en'}</span><span>{layerText}</span><span>Werkzeug Ø {operation.tool.diameterMm.toFixed(3)} mm</span><span>{validation.passes} Zustellung{validation.passes===1?'':'en'} je Bohrung</span></div>
<div class="checks"><div><strong>Geometrie</strong><p>Jeder ausgewählte native DXF-Kreis definiert genau eine Bohrachse über seinen Mittelpunkt.</p></div><div><strong>Maschinenstrategie</strong><p>Explizite G0/G1-Bewegungen: Safe-Z → XY → Bohren → Rückzug. Keine controllerabhängigen Canned Cycles.</p></div><div><strong>Tiefe</strong><p>{operation.totalDepthMm.toFixed(3)} mm Gesamttiefe · max. {operation.stepDownMm.toFixed(3)} mm je Zustellung · Eintauchen {operation.plungeMmMin} mm/min.</p></div></div>
{#each errors as message}<p class="error"><strong>FAIL</strong> {message}</p>{/each}{#each warnings as message}<p class="warning"><strong>Hinweis</strong> {message}</p>{/each}
<p class="note"><strong>Gate 9B:</strong> Der Preflight prüft Auswahl, Werkzeug, Tiefe, Zustellung, WCS, Schnittdaten und Sicherheits-Z vor der Maschinenfreigabe.</p>
<style>.eyebrow{font-size:.72rem;letter-spacing:.16em;text-transform:uppercase;color:#7a7d78;margin:0 0 .5rem}.release{display:grid;gap:4px;padding:12px 14px;margin:12px 0 14px;background:#f3f3f0;border-left:2px solid #999}.release strong{font-size:.72rem;letter-spacing:.08em}.release.pass strong{color:#2f6b4d}.release.warn strong{color:#9a6a19}.release.fail strong{color:#a13f38}.facts{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:14px}.facts span{padding:6px 8px;border-radius:6px;background:#eeefeb;font-size:.75rem;color:#555d58}.checks{display:grid;gap:8px}.checks div,.note,.error,.warning{padding:10px 12px;font-size:.8rem;line-height:1.4}.checks div,.note{background:#f3f3f0;color:#666b66}.checks p{margin:4px 0 0}.error{background:#fff0ee;color:#8d3029}.warning{background:#fbf5e8;color:#76591f}</style>
