<script lang="ts">
  import { onMount } from 'svelte';
  import type { Curve2, ImportSummary, Point2, StockDefinition, PartPlacement, WorkCoordinateSystem } from './types';
  export let summary: ImportSummary; export let stock: StockDefinition; export let placement: PartPlacement; export let wcs: WorkCoordinateSystem;
  type P2={x:number;y:number}; type P3={x:number;y:number;z:number}; type View={yaw:number;pitch:number};
  const width=1000,height=650,pad=54; let viewport:SVGSVGElement;
  let yaw=-.72,pitch=.48,zoom=1,viewX=0,viewY=0,dragging=false,lastX=0,lastY=0,dragMode:'orbit'|'pan'='orbit',inputEvents=0,lastInput='keins';
  const finite=(p:P2)=>Number.isFinite(p.x)&&Number.isFinite(p.y);
  function fit(points:P2[]){const p=points.filter(finite);if(!p.length)return(q:P2)=>q;const xs=p.map(q=>q.x),ys=p.map(q=>q.y),a=Math.min(...xs),b=Math.max(...xs),c=Math.min(...ys),d=Math.max(...ys),sx=Math.max(b-a,1e-9),sy=Math.max(d-c,1e-9),s=Math.min((width-2*pad)/sx,(height-2*pad)/sy),ox=(width-sx*s)/2,oy=(height-sy*s)/2;return(q:P2)=>({x:ox+(q.x-a)*s,y:height-(oy+(q.y-c)*s)});}
  function sample(c:Curve2):Point2[]{if(c.kind==='line')return[c.start,c.end];if(c.kind==='polyline')return c.points;if(c.kind==='circle')return Array.from({length:65},(_,i)=>{const a=i/64*Math.PI*2;return{x:c.center.x+Math.cos(a)*c.radius,y:c.center.y+Math.sin(a)*c.radius}});if(c.kind==='arc'){let a=c.startAngleDeg,b=c.endAngleDeg;while(b<a)b+=360;return Array.from({length:33},(_,i)=>{const r=(a+(b-a)*i/32)*Math.PI/180;return{x:c.center.x+Math.cos(r)*c.radius,y:c.center.y+Math.sin(r)*c.radius}})}return[];}
  const path=(p:P2[],closed=false)=>p.map((q,i)=>`${i?'L':'M'}${q.x.toFixed(2)},${q.y.toFixed(2)}`).join(' ')+(closed?' Z':'');
  function bounds3(p:P3[]){const x=p.map(q=>q.x),y=p.map(q=>q.y),z=p.map(q=>q.z);return{minX:Math.min(...x),maxX:Math.max(...x),minY:Math.min(...y),maxY:Math.max(...y),minZ:Math.min(...z)}}
  function bounds2(p:P2[]){const x=p.map(q=>q.x),y=p.map(q=>q.y);return{minX:Math.min(...x),maxX:Math.max(...x),minY:Math.min(...y),maxY:Math.max(...y)}}
  function place(a:number,b:number,c:number,d:number){const pw=b-a,ph=d-c,tx=placement.horizontal==='left'?0:placement.horizontal==='right'?stock.width-pw:(stock.width-pw)/2,ty=placement.vertical==='front'?0:placement.vertical==='back'?stock.height-ph:(stock.height-ph)/2;return{dx:tx-a+placement.offsetX,dy:ty-c+placement.offsetY}}
  function project(p:P3,v:View):P2{const cy=Math.cos(v.yaw),sy=Math.sin(v.yaw),cp=Math.cos(v.pitch),sp=Math.sin(v.pitch),x=p.x*cy-p.y*sy,y=p.x*sy+p.y*cy;return{x,y:(y*sp+p.z*cp)+(y*cp-p.z*sp)*.08}}
  function wcsPoint():P3{return{x:wcs.x==='left'?0:wcs.x==='right'?stock.width:stock.width/2,y:wcs.y==='front'?0:wcs.y==='back'?stock.height:stock.height/2,z:wcs.z==='top'?stock.thickness:0}}
  function scene3d(v:View){const a=summary.brep?.displayVertices??[],raw:P3[]=[];for(let i=0;i+2<a.length;i+=3)raw.push({x:a[i],y:a[i+1],z:a[i+2]});if(!raw.length)return null;const b=bounds3(raw),p=place(b.minX,b.maxX,b.minY,b.maxY),part=raw.map(q=>({x:q.x+p.dx,y:q.y+p.dy,z:q.z-b.minZ+placement.offsetZ})),m=Math.max(stock.width,stock.height)*.12+10,plane:P3[]=[{x:-m,y:-m,z:0},{x:stock.width+m,y:-m,z:0},{x:stock.width+m,y:stock.height+m,z:0},{x:-m,y:stock.height+m,z:0}],box:P3[]=[{x:0,y:0,z:0},{x:stock.width,y:0,z:0},{x:stock.width,y:stock.height,z:0},{x:0,y:stock.height,z:0},{x:0,y:0,z:stock.thickness},{x:stock.width,y:0,z:stock.thickness},{x:stock.width,y:stock.height,z:stock.thickness},{x:0,y:stock.height,z:stock.thickness}],wp=wcsPoint(),al=Math.max(35,Math.min(stock.width,stock.height)*.55),axes=[wp,{x:wp.x+al,y:wp.y,z:wp.z},wp,{x:wp.x,y:wp.y+al,z:wp.z},wp,{x:wp.x,y:wp.y,z:wp.z+al}],pp=part.map(q=>project(q,v)),pl=plane.map(q=>project(q,v)),pb=box.map(q=>project(q,v)),pa=axes.map(q=>project(q,v)),pw=project(wp,v),map=fit([...pp,...pl,...pb,...pa]),fp=pp.map(map),fpl=pl.map(map),fb=pb.map(map),fa=pa.map(map),fw=map(pw);let partPath='';for(let i=0;i+2<fp.length;i+=3)partPath+=path([fp[i],fp[i+1],fp[i+2]],true)+' ';const e=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]];return{partPath,plane:path(fpl,true),stock:e.map(([i,j])=>path([fb[i],fb[j]])),axes:[path([fa[0],fa[1]]),path([fa[2],fa[3]]),path([fa[4],fa[5]])],labels:[fa[1],fa[3],fa[5]],wcs:fw}}
  function scene2d(){const curves=summary.planarGeometry?.curves??[],ss=curves.map(sample),flat=ss.flat();if(!flat.length)return null;const b=bounds2(flat),p=place(b.minX,b.maxX,b.minY,b.maxY),placed=ss.map(a=>a.map(q=>({x:q.x+p.dx,y:q.y+p.dy}))),m=Math.max(stock.width,stock.height)*.12+10,plane=[{x:-m,y:-m},{x:stock.width+m,y:-m},{x:stock.width+m,y:stock.height+m},{x:-m,y:stock.height+m}],box=[{x:0,y:0},{x:stock.width,y:0},{x:stock.width,y:stock.height},{x:0,y:stock.height}],map=fit([...placed.flat(),...plane]),wp=map({x:wcs.x==='left'?0:wcs.x==='right'?stock.width:stock.width/2,y:wcs.y==='front'?0:wcs.y==='back'?stock.height:stock.height/2});return{paths:placed.map((a,i)=>path(a.map(map),curves[i]?.kind==='circle'||(curves[i]?.kind==='polyline'&&curves[i].closed))).filter(Boolean),plane:path(plane.map(map),true),stock:path(box.map(map),true),wcs:wp}}
  function currentViewBox(){const w=width/zoom,h=height/zoom;return`${viewX+(width-w)/2} ${viewY+(height-h)/2} ${w} ${h}`}
  function applyViewBox(){if(viewport)viewport.setAttribute('viewBox',currentViewBox())}
  const mark=(s:string)=>{inputEvents++;lastInput=s}; function setZoom(z:number){zoom=Math.max(.25,Math.min(6,z));mark(`zoom ${zoom.toFixed(2)}`);queueMicrotask(applyViewBox)}
  function down(e:PointerEvent){if(summary.kind!=='step')return;dragging=true;dragMode=e.shiftKey||e.button===1||e.button===2?'pan':'orbit';lastX=e.clientX;lastY=e.clientY;viewport.setPointerCapture(e.pointerId);mark('pointerdown')}
  function move(e:PointerEvent){if(!dragging||summary.kind!=='step')return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;if(dragMode==='orbit'){yaw+=dx*.008;pitch=Math.max(-1.5,Math.min(1.5,pitch-dy*.008))}else{viewX-=dx/zoom;viewY-=dy/zoom;queueMicrotask(applyViewBox)}}
  function up(e:PointerEvent){dragging=false;if(viewport.hasPointerCapture(e.pointerId))viewport.releasePointerCapture(e.pointerId)} function wheel(e:WheelEvent){if(summary.kind!=='step')return;e.preventDefault();setZoom(zoom*Math.exp(-e.deltaY*.002))} function reset(){yaw=-.72;pitch=.48;zoom=1;viewX=viewY=0;mark('reset');queueMicrotask(applyViewBox)}
  onMount(()=>{const e=viewport,cm=(x:MouseEvent)=>x.preventDefault();e.addEventListener('pointerdown',down);e.addEventListener('pointermove',move);e.addEventListener('pointerup',up);e.addEventListener('pointercancel',up);e.addEventListener('wheel',wheel,{passive:false});e.addEventListener('contextmenu',cm);applyViewBox();return()=>{e.removeEventListener('pointerdown',down);e.removeEventListener('pointermove',move);e.removeEventListener('pointerup',up);e.removeEventListener('pointercancel',up);e.removeEventListener('wheel',wheel);e.removeEventListener('contextmenu',cm)}}); $: s3=scene3d({yaw,pitch}); $: s2=scene2d();
</script>
<div class="geometry-view"><svg bind:this={viewport} viewBox="0 0 1000 650" class:interactive={summary.kind==='step'}>{#if summary.kind==='dxf'&&s2}<path d={s2.plane} class="setup-plane"/><path d={s2.stock} class="stock"/>{#each s2.paths as p}<path d={p} class="dxf"/>{/each}<circle cx={s2.wcs.x} cy={s2.wcs.y} r="9" class="wcs-marker"/><text x={s2.wcs.x+13} y={s2.wcs.y-10} class="wcs-label">WCS · X0 Y0</text>{:else if s3}<path d={s3.plane} class="setup-plane"/>{#each s3.stock as p}<path d={p} class="stock"/>{/each}<path d={s3.axes[0]} class="axis x"/><path d={s3.axes[1]} class="axis y"/><path d={s3.axes[2]} class="axis z"/><text x={s3.labels[0].x+7} y={s3.labels[0].y-5}>X</text><text x={s3.labels[1].x+7} y={s3.labels[1].y-5}>Y</text><text x={s3.labels[2].x+7} y={s3.labels[2].y-5}>Z</text><circle cx={s3.wcs.x} cy={s3.wcs.y} r="10" class="wcs-marker"/><circle cx={s3.wcs.x} cy={s3.wcs.y} r="3" class="wcs-dot"/><text x={s3.wcs.x+14} y={s3.wcs.y-12} class="wcs-label">WCS · X0 Y0 Z0</text><path d={s3.partPath} class="step"/>{/if}</svg><div class="geometry-caption"><strong>{summary.kind==='step'?'BRep · Rohling · WCS':'2D-Geometrie · Rohling · WCS'}</strong>{#if summary.kind==='step'}<span class="help"><button onclick={()=>{yaw-=.3;mark('orbit')}}>↺</button><button onclick={()=>{yaw+=.3;mark('orbit')}}>↻</button><button onclick={()=>setZoom(zoom*1.25)}>+</button><button onclick={()=>setZoom(zoom/1.25)}>−</button><button onclick={reset}>Reset</button><span>Input {inputEvents} · {lastInput}</span></span>{/if}</div></div>
<style>.geometry-view{width:min(92%,1100px);margin:auto}svg{width:100%;display:block;touch-action:none;user-select:none}svg.interactive{cursor:grab}svg.interactive:active{cursor:grabbing}.setup-plane{fill:rgba(255,255,255,.2);stroke:rgba(70,80,75,.18);stroke-width:1.2;vector-effect:non-scaling-stroke;pointer-events:none}.stock{fill:none;stroke:rgba(93,105,99,.55);stroke-width:1.5;stroke-dasharray:5 4;vector-effect:non-scaling-stroke;pointer-events:none}.dxf{fill:none;stroke:#26342e;stroke-width:2.2;vector-effect:non-scaling-stroke;pointer-events:none}.step{fill:rgba(72,94,84,.16);stroke:rgba(38,52,46,.42);stroke-width:.7;vector-effect:non-scaling-stroke;pointer-events:none}.axis{fill:none;stroke-width:2.2;vector-effect:non-scaling-stroke;pointer-events:none}.axis.x{stroke:#b1453b}.axis.y{stroke:#468058}.axis.z{stroke:#40669f}text{font-size:15px;font-weight:650;fill:#4c5651;pointer-events:none}.wcs-marker{fill:rgba(208,128,43,.12);stroke:#c27528;stroke-width:2.5;vector-effect:non-scaling-stroke;pointer-events:none}.wcs-dot{fill:#c27528;pointer-events:none}.wcs-label{fill:#9a5c1e;font-size:13px;font-weight:700;pointer-events:none}.geometry-caption{display:flex;justify-content:space-between;gap:24px;padding:0 5% 12px;color:#65706b;font-size:12px;align-items:center}.geometry-caption strong{color:#34423c;font-weight:600}.help{display:flex;align-items:center;gap:7px}.help button{min-width:28px;border:1px solid rgba(52,66,60,.22);border-radius:7px;background:rgba(255,255,255,.55);padding:3px 7px;color:#34423c;cursor:pointer;font:inherit}</style>