import type { CamOperation, ImportSummary, StockDefinition, StockMode, PartPlacement, PartOrientation, WorkCoordinateSystem } from './types';
import { generateFacingGcode } from './facingGcode';
import { generateContourGcode, buildDxfContourCanonicalState } from './gcode';
import { validateCarveOperation } from './carveMath';
import { validateDrillOperation } from './drillGcode';
import { validateOperationGrammar } from './validationGrammar';
import { validateCanonicalToolpath } from './canonicalPreflight';
import { buildFacingToolpath } from './facingToolpath';
import { buildStepContourOperationState } from './stepContourOperation';
import { buildPocketOperationState } from './pocketOperationState';
import { buildCarveCanonicalToolpath } from './carveCanonicalToolpath';
import { buildDrillCanonicalToolpath } from './drillCanonicalToolpath';
import { buildStepDrillOperationState } from './stepDrillOperation';
import { buildZLevelOperationState, zLevelMode } from './zLevelOperationState';
import { buildSurfaceFinishingOperationState } from './surfaceFinishingOperation';
import { buildDxfMultiTargetContourState, buildDxfMultiTargetPocketState } from './dxfMultiTargetToolpath';
import { normalizeDxfTargetIds } from './dxfMultiTargetSelection';
import { toolIdentityKey } from './toolIdentity.js';
import { simulateStockHeightfield, type StockSimulationOperation } from './stockSimulation';
import { validateToolAssemblyAgainstRestStock } from './toolAssemblyCollision';
import { validateToolAssemblyAgainstFixtures, type FixtureVolume, type FixtureCollisionKind } from './fixtureCollision';
import { validateMachineEnvelope, type MachineEnvelope, type MachineWcsOrigin } from './machineEnvelope';
import { materializeSafeMotionChain, buildJobSafeTransitions } from './safeMotionChain';
import { validateSpindleHeadAgainstFixtures, type SpindleHeadGeometry, type SpindleHeadCollisionKind } from './spindleHeadCollision';
import type { CanonicalToolpath } from './canonicalToolpath';

export type JobPreflightLevel='pass'|'warn'|'fail';
export type JobPreflightToolAssembly={level:JobPreflightLevel;cuttingLengthMm:number;stickoutMm:number;shaftDiameterMm:number;holderDiameterMm:number;errors:string[];warnings:string[]}|null;
export type JobPreflightFixtureCollision={level:JobPreflightLevel;checkedFixtures:number;hits:number;kinds:FixtureCollisionKind[];errors:string[]}|null;
export type JobPreflightMachineEnvelope={level:JobPreflightLevel;checkedPoints:number;limitHits:number;marginHits:number;usesExplicitMotions:boolean;errors:string[];warnings:string[]}|null;
export type JobPreflightSpindleHead={level:JobPreflightLevel;checkedFixtures:number;checkedMotions:number;hits:number;kinds:SpindleHeadCollisionKind[];errors:string[];warnings:string[]}|null;
export type JobPreflightOperation={id:string;index:number;kind:CamOperation['kind'];label:string;detail:string;canonical:string;level:JobPreflightLevel;errors:string[];warnings:string[];toolAssembly:JobPreflightToolAssembly;fixtureCollision:JobPreflightFixtureCollision;machineEnvelope:JobPreflightMachineEnvelope;spindleHead:JobPreflightSpindleHead;toolpath:CanonicalToolpath|null};
export type JobPreflightStockSimulation={cellSizeMm:number;columns:number;rows:number;initialVolumeMm3:number;remainingVolumeMm3:number;removedVolumeMm3:number;removedPercent:number;touchedCells:number;operationCount:number};
export type JobPreflightResult={level:JobPreflightLevel;operations:JobPreflightOperation[];enabledCount:number;toolChanges:number;errors:string[];warnings:string[];stockSimulation:JobPreflightStockSimulation|null};
const kindLabel=(kind:CamOperation['kind'])=>kind==='facing'?'Planen':kind==='contour'?'Kontur':kind==='pocket'?'Tasche':kind==='carve'?'Carve':kind==='drill'?'Bohren':kind==='surface-finishing'?'3D Schlichten':'Z-Level Schruppen';
const toolKey=(op:CamOperation)=>toolIdentityKey(op);const unique=(items:string[])=>[...new Set(items)];

export function validateJob(args:{summary:ImportSummary;stock:StockDefinition;stockMode:StockMode;placement:PartPlacement;orientation:PartOrientation;wcs:WorkCoordinateSystem;operations:CamOperation[];fixtures?:FixtureVolume[];machineEnvelope?:MachineEnvelope|null;machineWcsOrigin?:MachineWcsOrigin|null;spindleHead?:SpindleHeadGeometry|null}):JobPreflightResult{
  const {summary,stock,stockMode,placement,orientation,wcs}=args,fixtures=args.fixtures??[],machineEnvelopeConfig=args.machineEnvelope??null,machineWcsOrigin=args.machineWcsOrigin??null,spindleHeadConfig=args.spindleHead??null,enabled=args.operations.filter(op=>op.enabled!==false),operations:JobPreflightOperation[]=[],errors:string[]=[],warnings:string[]=[],stockSimulationOperations:StockSimulationOperation[]=[];
  enabled.forEach((operation,index)=>{
    let opErrors:string[]=[],opWarnings:string[]=[],detail='',canonicalToolpath=null,toolAssembly:JobPreflightToolAssembly=null,fixtureCollision:JobPreflightFixtureCollision=null,machineEnvelope:JobPreflightMachineEnvelope=null,spindleHead:JobPreflightSpindleHead=null;
    if(operation.kind==='facing'){const r=generateFacingGcode({stock,stockMode,wcs,operation});opErrors=[...r.errors];opWarnings=[...r.warnings];detail=`${operation.direction==='x'?'X-Raster':'Y-Raster'} · Ø ${operation.tool.diameterMm.toFixed(3)} mm · ${operation.totalDepthMm.toFixed(3)} mm Abtrag`;if(r.ok)canonicalToolpath=buildFacingToolpath({stock,wcs,operation}).toolpath;}
    else if(operation.kind==='carve'){const r=validateCarveOperation(summary,operation);opErrors=[...r.errors];opWarnings=[...r.warnings];detail=`${r.segments.length} Linien · Ø ${operation.tool.diameterMm.toFixed(3)} mm · ${operation.totalDepthMm.toFixed(3)} mm tief`;if(!opErrors.length)canonicalToolpath=buildCarveCanonicalToolpath({summary,stock,stockMode,placement,orientation,wcs,operation});}
    else if(operation.kind==='drill'){
      if(summary.kind==='step'){const state=buildStepDrillOperationState({summary,stock,stockMode,placement,orientation,wcs,operation,previousToolpaths:stockSimulationOperations.map(entry=>entry.toolpath)});opErrors=[...state.errors];opWarnings=[...state.warnings];canonicalToolpath=state.toolpath;detail=`STEP BRep · ${operation.method==='helical-mill'?'Helixfräsen':'Bohren'} · ${state.holes.length} Position${state.holes.length===1?'':'en'} · Werkzeug Ø ${operation.tool.diameterMm.toFixed(3)} mm · Start aus aktuellem Reststock`;}
      else{const r=validateDrillOperation(summary,operation);opErrors=[...r.errors];opWarnings=[...r.warnings];detail=`${operation.method==='helical-mill'?'Helixfräsen':'Bohren'} · ${r.holeCount} Position${r.holeCount===1?'':'en'} · Werkzeug Ø ${operation.tool.diameterMm.toFixed(3)} mm · ${operation.totalDepthMm.toFixed(3)} mm tief`;if(!opErrors.length)canonicalToolpath=buildDrillCanonicalToolpath({summary,stock,stockMode,placement,orientation,wcs,operation});}
    }
    else if(operation.kind==='pocket'){
      const state=summary.kind==='dxf'?buildDxfMultiTargetPocketState({summary,stock,stockMode,placement,orientation,wcs,operation,previousToolpaths:stockSimulationOperations.map(entry=>entry.toolpath)}):buildPocketOperationState({summary,stock,stockMode,placement,orientation,wcs,operation,previousToolpaths:stockSimulationOperations.map(entry=>entry.toolpath)});
      opErrors=[...state.errors];opWarnings=[...state.warnings];canonicalToolpath=state.toolpath;
      detail=summary.kind==='step'
        ?`STEP BRep · planare Face${operation.stepFaceId!=null?` ${operation.stepFaceId}`:''} · Ø ${operation.tool.diameterMm.toFixed(3)} mm · Ziel ${state.targetDepthMm?.toFixed(3)??'—'} mm`
        :`DXF Tasche · ${normalizeDxfTargetIds(operation).length} Ziel${normalizeDxfTargetIds(operation).length===1?'':'e'} · Ø ${operation.tool.diameterMm.toFixed(3)} mm · ${operation.totalDepthMm.toFixed(3)} mm tief`;
      if((operation.radialAllowanceMm??0)>0||(operation.axialAllowanceMm??0)>0)detail+=` · Aufmaß R${Number(operation.radialAllowanceMm??0).toFixed(3)} / Z${Number(operation.axialAllowanceMm??0).toFixed(3)} mm`;
      if(operation.finishPassEnabled)detail+=` · ${Math.max(1,Math.floor(operation.finishPassCount??1))} Schlichtdurchgang${Math.max(1,Math.floor(operation.finishPassCount??1))===1?'':'e'}`;
      if(operation.stockAwareRoughingEnabled)detail+=` · Stock-aware ${operation.maxRadialEngagementPercent??35}% radial`;
      if(operation.restMachiningEnabled){const source=enabled.find(op=>op.id===operation.restFromOperationId);detail+=` · Restmaterial${source?` aus ${source.name}`:''}`;}
    }
    else if(operation.kind==='surface-finishing'){detail=`3D Schlichten · ${operation.faceIds.length} Fläche${operation.faceIds.length===1?'':'n'} · ${operation.direction==='x'?'Parallel X':'Parallel Y'} · Ø ${operation.tool.diameterMm.toFixed(3)} mm · ${operation.stepoverPercent}% Stepover`;const reconstructed=buildSurfaceFinishingOperationState({summary,stock,placement,orientation,wcs,operation});opErrors.push(...reconstructed.errors);opWarnings.push(...reconstructed.warnings);if(reconstructed.ok&&reconstructed.toolpath){canonicalToolpath=reconstructed.toolpath;detail+=` · ${reconstructed.chainCount} Schlichtketten · ${reconstructed.contactPointCount} Kontaktpunkte`;}}
    else if(operation.kind==='z-level-roughing'){const mode=zLevelMode(operation),islands=mode==='face-target'?((operation.islandMode??'preserve')==='clear'?' · Inneninseln mit schruppen':' · Inneninseln stehen lassen'):'';detail=`${mode==='model'?'Modell · Stock−Model':'Face Target'}${islands} · Ø ${operation.tool.diameterMm.toFixed(3)} mm · ${operation.stepDownMm.toFixed(3)} mm Zustellung · ${operation.stepoverPercent}% Stepover · ${operation.finishAllowanceMm.toFixed(3)} mm Aufmaß`;const reconstructed=buildZLevelOperationState({summary,stock,placement,orientation,wcs,operation});opErrors.push(...reconstructed.errors);opWarnings.push(...reconstructed.warnings);if(reconstructed.toolpath){canonicalToolpath=reconstructed.toolpath;}}
    else if(summary.kind==='step'){const state=buildStepContourOperationState({summary,stock,stockMode,placement,orientation,wcs,operation,previousToolpaths:stockSimulationOperations.map(entry=>entry.toolpath)});opErrors=[...state.errors];opWarnings=[...state.warnings];canonicalToolpath=state.toolpath;const selected=state.selected;detail=`STEP BRep · geschlossene Wire${selected?` ${selected.wireId}`:''} · ${operation.side==='outside'?'Außen':operation.side==='inside'?'Innen':'Auf Linie'} · Ø ${operation.tool.diameterMm.toFixed(3)} mm · ${operation.totalDepthMm.toFixed(3)} mm tief`;}
    else{const state=buildDxfMultiTargetContourState({summary,stock,stockMode,placement,orientation,wcs,operation});opErrors=[...state.errors];opWarnings=[...state.warnings];const excluded=operation.excludedSegmentIds??[],topology=operation.topology==='open'?'offene DXF-Kontur':excluded.length?`aufgebrochen · ${excluded.length} Strecke${excluded.length===1?'':'n'} aus`:'geschlossen',side=operation.topology==='open'?(operation.openSide==='left'?'Links':operation.openSide==='right'?'Rechts':'Auf Linie'):(operation.side==='outside'?'Außen':operation.side==='inside'?'Innen':'Auf Linie');detail=`${topology} · ${side} · Ø ${operation.tool.diameterMm.toFixed(3)} mm · ${operation.totalDepthMm.toFixed(3)} mm tief`;if(state.ok)canonicalToolpath=state.toolpath;}
    for(const check of validateOperationGrammar(operation,stock,stockMode,wcs)){if(check.level==='fail')opErrors.push(`${check.title}: ${check.detail}`);else if(check.level==='warn')opWarnings.push(`${check.title}: ${check.detail}`);}

    if(canonicalToolpath&&!opErrors.length){const safeChain=materializeSafeMotionChain({toolpath:canonicalToolpath,safeZMm:operation.safeZMm});opErrors.push(...safeChain.errors.map(message=>`Safe Motion 004T: ${message}`));opWarnings.push(...safeChain.warnings.map(message=>`Safe Motion 004T: ${message}`));if(safeChain.toolpath){canonicalToolpath=safeChain.toolpath;detail+=` · 004T ${safeChain.motionCount} vollständige XYZ-Motions`;}}
    const canonical=validateCanonicalToolpath(canonicalToolpath);if(!opErrors.length){opErrors.push(...canonical.errors.map(message=>`Kanonischer Werkzeugweg: ${message}`));opWarnings.push(...canonical.warnings.map(message=>`Kanonischer Werkzeugweg: ${message}`));}
    if(canonicalToolpath&&!opErrors.length&&stockMode!=='none'&&wcs.z==='top'){const t=operation.tool;if(t.cuttingLengthMm&&t.stickoutMm&&t.shaftDiameterMm&&t.holderDiameterMm){const holder=validateToolAssemblyAgainstRestStock({stock,wcs,previousOperations:stockSimulationOperations,toolpath:canonicalToolpath,assembly:{cuttingLengthMm:t.cuttingLengthMm,stickoutMm:t.stickoutMm,shankDiameterMm:t.shaftDiameterMm,holderDiameterMm:t.holderDiameterMm}});opErrors.push(...holder.errors.map(message=>`Werkzeugbaugruppe: ${message}`));opWarnings.push(...holder.warnings.map(message=>`Werkzeugbaugruppe: ${message}`));const holderLevel:JobPreflightLevel=holder.errors.length?'fail':holder.warnings.length?'warn':'pass';toolAssembly={level:holderLevel,cuttingLengthMm:t.cuttingLengthMm,stickoutMm:t.stickoutMm,shaftDiameterMm:t.shaftDiameterMm,holderDiameterMm:t.holderDiameterMm,errors:[...holder.errors],warnings:[...holder.warnings]};detail+=` · 004Q Halter Ø ${t.holderDiameterMm.toFixed(1)} mm · Auskragung ${t.stickoutMm.toFixed(1)} mm`;}else opWarnings.push('Werkzeugbaugruppe: Für 004Q fehlen Schneidenlänge, Auskragung, Schaft- oder Halterdurchmesser.');}

    if(canonicalToolpath&&!opErrors.length&&fixtures.some(f=>f.enabled!==false)){const t=operation.tool;if(t.cuttingLengthMm&&t.stickoutMm&&t.shaftDiameterMm&&t.holderDiameterMm){const fixtureResult=validateToolAssemblyAgainstFixtures({toolpath:canonicalToolpath,fixtures,assembly:{cuttingLengthMm:t.cuttingLengthMm,stickoutMm:t.stickoutMm,shankDiameterMm:t.shaftDiameterMm,holderDiameterMm:t.holderDiameterMm}});opErrors.push(...fixtureResult.errors.map(message=>`Spannmittel: ${message}`));opWarnings.push(...fixtureResult.warnings.map(message=>`Spannmittel: ${message}`));const kinds=[...new Set(fixtureResult.hits.map(hit=>hit.kind))];fixtureCollision={level:fixtureResult.errors.length?'fail':fixtureResult.warnings.length?'warn':'pass',checkedFixtures:fixtureResult.checkedFixtures,hits:fixtureResult.hits.length,kinds,errors:[...fixtureResult.errors]};detail+=` · 004R ${fixtureResult.checkedFixtures} Spannmittel geprüft`;}else opWarnings.push('Spannmittelprüfung: Werkzeugbaugruppen-Geometrie für 004R unvollständig.');}

    if(canonicalToolpath&&!opErrors.length&&spindleHeadConfig&&fixtures.some(f=>f.enabled!==false)){const result=validateSpindleHeadAgainstFixtures({toolpath:canonicalToolpath,fixtures,head:spindleHeadConfig});opErrors.push(...result.errors.map(message=>`Spindelkopf: ${message}`));opWarnings.push(...result.warnings.map(message=>`Spindelkopf: ${message}`));spindleHead={level:result.errors.length?'fail':result.warnings.length?'warn':'pass',checkedFixtures:result.checkedFixtures,checkedMotions:result.checkedMotions,hits:result.hits.length,kinds:[...new Set(result.hits.map(hit=>hit.kind))],errors:[...result.errors],warnings:[...result.warnings]};detail+=` · 004U ${result.hits.length?`${result.hits.length} Spindelkopf-Treffer`:'Spindelkopf frei'}`;}
    if(canonicalToolpath&&!opErrors.length&&machineEnvelopeConfig&&machineWcsOrigin){const machine=validateMachineEnvelope({toolpath:canonicalToolpath,envelope:machineEnvelopeConfig,wcsOrigin:machineWcsOrigin,safeZMm:operation.safeZMm});opErrors.push(...machine.errors.map(message=>`Maschinenraum: ${message}`));opWarnings.push(...machine.warnings.map(message=>`Maschinenraum: ${message}`));const limitHits=machine.hits.filter(hit=>hit.kind==='limit').length,marginHits=machine.hits.filter(hit=>hit.kind==='margin').length;machineEnvelope={level:machine.errors.length?'fail':machine.warnings.length?'warn':'pass',checkedPoints:machine.checkedPoints,limitHits,marginHits,usesExplicitMotions:machine.usesExplicitMotions,errors:[...machine.errors],warnings:[...machine.warnings]};detail+=` · 004S ${machine.checkedPoints} Maschinenpunkte geprüft`;}
    opErrors=unique(opErrors);opWarnings=unique(opWarnings);if(canonicalToolpath&&!opErrors.length)stockSimulationOperations.push({operationId:operation.id,toolpath:canonicalToolpath});const level:JobPreflightLevel=opErrors.length?'fail':opWarnings.length?'warn':'pass',label=operation.name||kindLabel(operation.kind);operations.push({id:operation.id,index:index+1,kind:operation.kind,label,detail,canonical:canonical.summary,level,errors:opErrors,warnings:opWarnings,toolAssembly,fixtureCollision,machineEnvelope,spindleHead,toolpath:canonicalToolpath});errors.push(...opErrors.map(e=>`Bearbeitung ${index+1} (${kindLabel(operation.kind)}): ${e}`));warnings.push(...opWarnings.map(w=>`Bearbeitung ${index+1} (${kindLabel(operation.kind)}): ${w}`));
  });
  const transitionSource=operations.filter(op=>op.toolpath&&!op.errors.length).map(op=>({id:op.id,safeZMm:enabled.find(item=>item.id===op.id)?.safeZMm??0,toolpath:op.toolpath!}));
  const transitions=buildJobSafeTransitions({operations:transitionSource});
  errors.push(...transitions.errors.map(message=>`Safe Motion 004T Job: ${message}`));
  if(machineEnvelopeConfig&&machineWcsOrigin){
    for(const transition of transitions.transitions){
      if(!transition.motions.length)continue;
      const probe:CanonicalToolpath={version:1,operationKind:'contour',strategy:'contour',tool:{diameterMm:1},stepoverPercent:0,runs:[],motions:transition.motions};
      const check=validateMachineEnvelope({toolpath:probe,envelope:machineEnvelopeConfig,wcsOrigin:machineWcsOrigin,safeZMm:transition.motions[0].start.z});
      errors.push(...check.errors.map(message=>`Maschinenraum Übergang ${transition.fromOperationId} → ${transition.toOperationId}: ${message}`));
      warnings.push(...check.warnings.map(message=>`Maschinenraum Übergang ${transition.fromOperationId} → ${transition.toOperationId}: ${message}`));
    }
  }
  if(!enabled.length)errors.push('Der Gesamtjob enthält keine aktivierte Bearbeitung.');let toolChanges=0;for(let i=1;i<enabled.length;i++)if(toolKey(enabled[i])!==toolKey(enabled[i-1]))toolChanges++;const simulation=stockMode==='none'||wcs.z!=='top'?null:simulateStockHeightfield({stock,wcs,operations:stockSimulationOperations});if(stockMode!=='none'&&wcs.z!=='top')warnings.push('Stock-Simulation 004P ist bei Z-Null auf Rohlingunterseite noch nicht verfügbar.');if(simulation){errors.push(...simulation.errors.map(e=>`Stock-Simulation: ${e}`));warnings.push(...simulation.warnings.map(w=>`Stock-Simulation: ${w}`));}const stockSimulation=simulation&&simulation.ok?{cellSizeMm:simulation.cellSizeMm,columns:simulation.columns,rows:simulation.rows,initialVolumeMm3:simulation.initialVolumeMm3,remainingVolumeMm3:simulation.remainingVolumeMm3,removedVolumeMm3:simulation.removedVolumeMm3,removedPercent:simulation.removedPercent,touchedCells:simulation.touchedCells,operationCount:simulation.operationCount}:null;const level:JobPreflightLevel=errors.length?'fail':warnings.length?'warn':'pass';return{level,operations,enabledCount:enabled.length,toolChanges,errors,warnings,stockSimulation};
}
