<script lang="ts">
  import type { CamOperation, ImportSummary, StockDefinition, StockMode, PartPlacement, PartOrientation, WorkCoordinateSystem } from './types';
  import { validateJob } from './jobPreflight';
  import type { FixtureVolume } from './fixtureCollision';
  import type { MachineEnvelope, MachineWcsOrigin } from './machineEnvelope';
  export let summary:ImportSummary;export let stock:StockDefinition;export let stockMode:StockMode;export let placement:PartPlacement;export let orientation:PartOrientation;export let wcs:WorkCoordinateSystem;export let fixtures:FixtureVolume[]=[];export let machineEnvelope:MachineEnvelope|null=null;export let machineWcsOrigin:MachineWcsOrigin|null=null;export let operations:CamOperation[];
  $: result=validateJob({summary,stock,stockMode,placement,orientation,wcs,operations,fixtures,machineEnvelope,machineWcsOrigin});
</script>
<p class="eyebrow">05 · Prüfen</p><h2>Gesamtjob</h2>
<div class="overall" class:pass={result.level==='pass'} class:warn={result.level==='warn'} class:fail={result.level==='fail'}><strong>{result.level.toUpperCase()}</strong><span>{result.level==='pass'?'Alle Bearbeitungen besitzen eine freigegebene kanonische Werkzeugbahn.':result.level==='warn'?'Der Gesamtjob ist freigabefähig, enthält aber Hinweise.':'Mindestens eine Bearbeitung oder ihre kanonische Werkzeugbahn ist nicht freigegeben. Der Gesamtjob darf nicht ausgegeben werden.'}</span></div>
<div class="facts"><span>{result.enabledCount} Bearbeitungen</span><span>{result.toolChanges} Werkzeugwechsel</span><span>Operation → kanonischer Toolpath → Prüfen → Postprozessor</span></div>
<div class="operations">{#each result.operations as op}<div class="op"><span class="status" class:pass={op.level==='pass'} class:warn={op.level==='warn'} class:fail={op.level==='fail'}>{op.level.toUpperCase()}</span><div><strong>{String(op.index).padStart(2,'0')} · {op.label}</strong><p>{op.detail}</p><p class="canonical">Kanonisch · {op.canonical}</p>{#if op.toolAssembly}<div class="assembly" class:pass={op.toolAssembly.level==='pass'} class:warn={op.toolAssembly.level==='warn'} class:fail={op.toolAssembly.level==='fail'}><strong>004Q Werkzeugbaugruppe · {op.toolAssembly.level.toUpperCase()}</strong><span>Schneidenlänge {op.toolAssembly.cuttingLengthMm.toFixed(1)} mm · Auskragung {op.toolAssembly.stickoutMm.toFixed(1)} mm · Schaft Ø {op.toolAssembly.shaftDiameterMm.toFixed(1)} mm · Halter Ø {op.toolAssembly.holderDiameterMm.toFixed(1)} mm</span><span>{op.toolAssembly.level==='pass'?'Reichweite und Halterfreiraum im 2.5D-Reststockmodell freigegeben.':op.toolAssembly.level==='warn'?'Reichweite ist freigegeben, aber die Schneidenlänge erzeugt einen Hinweis.':'Werkzeugreichweite oder Halterfreiraum ist nicht freigegeben.'}</span></div>{/if}{#if op.fixtureCollision}<div class="fixture-check" class:pass={op.fixtureCollision.level==='pass'} class:fail={op.fixtureCollision.level==='fail'}><strong>004R Spannmittel · {op.fixtureCollision.level.toUpperCase()}</strong><span>{op.fixtureCollision.checkedFixtures} aktiv geprüft · {op.fixtureCollision.hits} Treffer · {op.fixtureCollision.kinds.length?op.fixtureCollision.kinds.map(kind=>kind==='cutter'?'Fräser':kind==='shank'?'Schaft':'Halter').join(' / '):'kein Konflikt'}</span></div>{/if}{#if op.machineEnvelope}<div class="machine-check" class:pass={op.machineEnvelope.level==='pass'} class:warn={op.machineEnvelope.level==='warn'} class:fail={op.machineEnvelope.level==='fail'}><strong>004S Maschinenraum · {op.machineEnvelope.level.toUpperCase()}</strong><span>{op.machineEnvelope.checkedPoints} Punkte geprüft · {op.machineEnvelope.limitHits} Grenzverletzung{op.machineEnvelope.limitHits===1?'':'en'} · {op.machineEnvelope.marginHits} Warnabstand-Treffer</span><span>{op.machineEnvelope.usesExplicitMotions?'Vollständige canonical motions verwendet.':'Fallback: Runs + Entry/Exit; vollständige Rapid-Kette noch nicht verfügbar.'}</span></div>{/if}{#each op.errors as message}<p class="message fail-text">{message}</p>{/each}{#each op.warnings as message}<p class="message warn-text">{message}</p>{/each}</div></div>{/each}</div>
<p class="note"><strong>Prüfregel:</strong> No blind toolpaths. Eine fachlich gültige Bearbeitung ist erst dann freigegeben, wenn auch ihre kanonische Werkzeug- bzw. Maschinenbahn vollständig erzeugt und geprüft werden kann. Ein einziges FAIL setzt den gesamten Job auf FAIL.</p>
<style>.eyebrow{font-size:.72rem;letter-spacing:.16em;text-transform:uppercase;color:#7a7d78;margin:0 0 .5rem}.overall{border-left:2px solid #aaa;background:#f3f3f0;padding:12px 14px;margin:12px 0;display:grid;gap:4px}.overall strong,.status{font-size:.72rem;letter-spacing:.08em}.overall.pass strong,.status.pass,.assembly.pass strong{color:#2f6b4d}.overall.warn strong,.status.warn,.assembly.warn strong{color:#9a6a19}.overall.fail strong,.status.fail,.assembly.fail strong{color:#a13f38}.facts{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 14px}.facts span{padding:6px 8px;border-radius:6px;background:#eeefeb;font-size:.75rem;color:#555d58}.operations{border-top:1px solid #deded8}.op{display:grid;grid-template-columns:52px 1fr;gap:10px;padding:12px 0;border-bottom:1px solid #deded8}.op strong{font-size:.86rem}.op p{margin:3px 0 0;color:#666b66;font-size:.8rem;line-height:1.35}.op .canonical{color:#315f69;font-size:.75rem}.status{padding-top:2px}.assembly{display:grid;gap:3px;margin-top:8px;padding:8px 10px;border-left:2px solid #aaa;background:#f6f6f3;font-size:.75rem;color:#666b66}.assembly.pass{border-left-color:#2f6b4d}.assembly.warn{border-left-color:#9a6a19}.assembly.fail{border-left-color:#a13f38}.assembly span{line-height:1.35}.fixture-check{display:grid;gap:3px;margin-top:8px;padding:8px 10px;border-left:2px solid #2f6b4d;background:#f6f6f3;font-size:.75rem;color:#666b66}.fixture-check.fail{border-left-color:#a13f38}.fixture-check.pass strong{color:#2f6b4d}.fixture-check.fail strong{color:#a13f38}.machine-check{display:grid;gap:3px;margin-top:8px;padding:8px 10px;border-left:2px solid #2f6b4d;background:#f6f6f3;font-size:.75rem;color:#666b66}.machine-check.warn{border-left-color:#9a6a19}.machine-check.fail{border-left-color:#a13f38}.machine-check.pass strong{color:#2f6b4d}.machine-check.warn strong{color:#9a6a19}.machine-check.fail strong{color:#a13f38}.message{padding:5px 7px;margin-top:6px!important;border-radius:5px}.fail-text{background:#fff0ee;color:#8d3029!important}.warn-text{background:#fbf5e8;color:#76591f!important}.note{margin-top:16px;padding:11px 12px;background:#f3f3f0;color:#666b66;font-size:.8rem;line-height:1.4}</style>
