<script lang="ts">
  import type { CamOperation, ImportSummary, StockDefinition, StockMode, PartPlacement, PartOrientation, WorkCoordinateSystem } from './types';
  import { validateJob } from './jobPreflight';
  export let summary:ImportSummary;export let stock:StockDefinition;export let stockMode:StockMode;export let placement:PartPlacement;export let orientation:PartOrientation;export let wcs:WorkCoordinateSystem;export let operations:CamOperation[];
  $: result=validateJob({summary,stock,stockMode,placement,orientation,wcs,operations});
</script>
<p class="eyebrow">05 · Prüfen</p><h2>Gesamtjob</h2>
<div class="overall" class:pass={result.level==='pass'} class:warn={result.level==='warn'} class:fail={result.level==='fail'}><strong>{result.level.toUpperCase()}</strong><span>{result.level==='pass'?'Alle Bearbeitungen besitzen eine freigegebene kanonische Werkzeugbahn.':result.level==='warn'?'Der Gesamtjob ist freigabefähig, enthält aber Hinweise.':'Mindestens eine Bearbeitung oder ihre kanonische Werkzeugbahn ist nicht freigegeben. Der Gesamtjob darf nicht ausgegeben werden.'}</span></div>
<div class="facts"><span>{result.enabledCount} Bearbeitungen</span><span>{result.toolChanges} Werkzeugwechsel</span><span>Operation → kanonischer Toolpath → Prüfen → Postprozessor</span></div>
<div class="operations">{#each result.operations as op}<div class="op"><span class="status" class:pass={op.level==='pass'} class:warn={op.level==='warn'} class:fail={op.level==='fail'}>{op.level.toUpperCase()}</span><div><strong>{String(op.index).padStart(2,'0')} · {op.label}</strong><p>{op.detail}</p><p class="canonical">Kanonisch · {op.canonical}</p>{#each op.errors as message}<p class="message fail-text">{message}</p>{/each}{#each op.warnings as message}<p class="message warn-text">{message}</p>{/each}</div></div>{/each}</div>
<p class="note"><strong>Prüfregel:</strong> No blind toolpaths. Eine fachlich gültige Bearbeitung ist erst dann freigegeben, wenn auch ihre kanonische Werkzeug- bzw. Maschinenbahn vollständig erzeugt und geprüft werden kann. Ein einziges FAIL setzt den gesamten Job auf FAIL.</p>
<style>.eyebrow{font-size:.72rem;letter-spacing:.16em;text-transform:uppercase;color:#7a7d78;margin:0 0 .5rem}.overall{border-left:2px solid #aaa;background:#f3f3f0;padding:12px 14px;margin:12px 0;display:grid;gap:4px}.overall strong,.status{font-size:.72rem;letter-spacing:.08em}.overall.pass strong,.status.pass{color:#2f6b4d}.overall.warn strong,.status.warn{color:#9a6a19}.overall.fail strong,.status.fail{color:#a13f38}.facts{display:flex;gap:6px;flex-wrap:wrap;margin:0 0 14px}.facts span{padding:6px 8px;border-radius:6px;background:#eeefeb;font-size:.75rem;color:#555d58}.operations{border-top:1px solid #deded8}.op{display:grid;grid-template-columns:52px 1fr;gap:10px;padding:12px 0;border-bottom:1px solid #deded8}.op strong{font-size:.86rem}.op p{margin:3px 0 0;color:#666b66;font-size:.8rem;line-height:1.35}.op .canonical{color:#315f69;font-size:.75rem}.status{padding-top:2px}.message{padding:5px 7px;margin-top:6px!important;border-radius:5px}.fail-text{background:#fff0ee;color:#8d3029!important}.warn-text{background:#fbf5e8;color:#76591f!important}.note{margin-top:16px;padding:11px 12px;background:#f3f3f0;color:#666b66;font-size:.8rem;line-height:1.4}</style>
