import type { CanonicalSpatialSegment, CanonicalToolpath, CanonicalToolpathSegment, ToolpathPoint2 } from './canonicalToolpath';
import { offsetPolygon, polygonArea, type P2 } from './contourMath';
import type { PocketOperation } from './types';

export type RegionPocketStrategy='concentric'|'parallel';
export type RegionPocketResult={toolpath:CanonicalToolpath|null;errors:string[];warnings:string[]};
const EPS=1e-6;
const dist=(a:P2,b:P2)=>Math.hypot(a.x-b.x,a.y-b.y);
const areaAbs=(p:P2[])=>Math.abs(polygonArea(p));
const chooseOffset=(poly:P2[],d:number,wantLarger:boolean)=>{const a=offsetPolygon(poly,d),b=offsetPolygon(poly,-d),aa=areaAbs(a),bb=areaAbs(b);return wantLarger?(aa>=bb?a:b):(aa<=bb?a:b);};
const closedLoop=(poly:P2[]):ToolpathPoint2[]=>{const out=poly.map(p=>({x:p.x,y:p.y}));if(out.length&&dist(out[0],out[out.length-1])>1e-5)out.push({...out[0]});return out;};
const lineSegments=(points:ToolpathPoint2[]):CanonicalToolpathSegment[]=>points.slice(1).map((end,i)=>({kind:'line',start:points[i],end}));

function pointSegmentDistance(p:P2,a:P2,b:P2){const dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy;if(l2<=EPS)return dist(p,a);const t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/l2));return Math.hypot(p.x-(a.x+t*dx),p.y-(a.y+t*dy));}
function distanceToBoundary(p:P2,poly:P2[]){let best=Infinity;for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length];best=Math.min(best,pointSegmentDistance(p,a,b));}return best;}
function pointInPolygon(p:P2,poly:P2[]){if(distanceToBoundary(p,poly)<=1e-5)return true;let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[j],b=poly[i];if((a.y>p.y)===(b.y>p.y))continue;const x=(b.x-a.x)*(p.y-a.y)/(b.y-a.y+1e-30)+a.x;if(p.x<x)inside=!inside;}return inside;}
function inRegion(p:P2,outer:P2[],islands:P2[][]){return pointInPolygon(p,outer)&&!islands.some(poly=>pointInPolygon(p,poly)&&distanceToBoundary(p,poly)>1e-5);}
function loopSafe(loop:P2[],outer:P2[],islands:P2[][]){return loop.length>=4&&loop.every(p=>inRegion(p,outer,islands));}
function centroid(poly:P2[]):P2{let twice=0,cx=0,cy=0;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[j],b=poly[i],cross=a.x*b.y-b.x*a.y;twice+=cross;cx+=(a.x+b.x)*cross;cy+=(a.y+b.y)*cross;}if(Math.abs(twice)<=EPS){const xs=poly.map(p=>p.x),ys=poly.map(p=>p.y);return{x:(Math.min(...xs)+Math.max(...xs))/2,y:(Math.min(...ys)+Math.max(...ys))/2};}return{x:cx/(3*twice),y:cy/(3*twice)};}
const circle=(c:P2,r:number)=>Array.from({length:97},(_,i)=>{const a=i/96*Math.PI*2;return{x:c.x+Math.cos(a)*r,y:c.y+Math.sin(a)*r};});

function parallelPaths(outer:P2[],islands:P2[][],stepover:number){const paths:ToolpathPoint2[][]=[];let shell=outer,guard=0;while(areaAbs(shell)>EPS&&guard++<512){const loop=closedLoop(shell);if(!loopSafe(loop,outer,islands))break;paths.push(loop);const next=chooseOffset(shell,stepover,false);if(areaAbs(next)>=areaAbs(shell)-EPS||areaAbs(next)<=EPS)break;shell=next;}for(const island of islands){let ring=island,prev=areaAbs(ring),i=0;while(i++<256){const next=chooseOffset(ring,stepover,true),a=areaAbs(next);if(a<=prev+EPS)break;const loop=closedLoop(next);if(!loopSafe(loop,outer,islands.filter(x=>x!==island)))break;paths.push(loop);ring=next;prev=a;}}return paths;}

function concentricPaths(outer:P2[],islands:P2[][],stepover:number){if(islands.length)return{paths:[] as ToolpathPoint2[][],error:'Kreisräumen ist für Taschen mit Inseln noch nicht freigegeben; verwende Raster oder Konturparallel.'};const c=centroid(outer);if(!pointInPolygon(c,outer))return{paths:[] as ToolpathPoint2[][],error:'Kreisräumen benötigt einen sicheren Mittelpunkt innerhalb der Taschenregion.'};const maxR=distanceToBoundary(c,outer);if(!(maxR>EPS))return{paths:[] as ToolpathPoint2[][],error:'Taschenregion ist für Kreisräumen zu klein.'};const paths:ToolpathPoint2[][]=[];for(let r=Math.min(stepover,maxR);r<=maxR+EPS;r+=stepover){const rr=Math.min(r,maxR),loop=circle(c,rr);if(loopSafe(loop,outer,[]))paths.push(loop);if(rr>=maxR-EPS)break;}
  // Ecken/Freiformbereiche: konturparallele Cleanup-Schalen von außen nach innen,
  // bis sie die bereits mit Kreisringen geräumte Kernzone sicher überdecken.
  let shell=outer,guard=0;while(areaAbs(shell)>EPS&&guard++<512){const radialMax=Math.max(...shell.map(p=>dist(p,c)));if(radialMax<=maxR+stepover*.5)break;const loop=closedLoop(shell);if(loopSafe(loop,outer,[]))paths.push(loop);const next=chooseOffset(shell,stepover,false);if(areaAbs(next)>=areaAbs(shell)-EPS||areaAbs(next)<=EPS)break;shell=next;}
  return{paths,error:null as string|null};}

function entryForPath(operation:PocketOperation,path:ToolpathPoint2[],zStart:number,zEnd:number):{segments?:CanonicalSpatialSegment[];error?:string}{if(operation.entry==='plunge')return{};if(path.length<2)return{error:'Einstieg benötigt eine ausreichend lange Taschenbahn.'};if(operation.entry==='ramp'){const available=dist(path[0],path[1]),required=Math.abs(zEnd-zStart)/Math.tan(operation.rampAngleDeg*Math.PI/180);if(!(available+EPS>=required))return{error:`Rampenwinkel ${operation.rampAngleDeg.toFixed(1)}° benötigt eine längere erste Bahn.`};const t=Math.min(1,required/available),end={x:path[0].x+(path[1].x-path[0].x)*t,y:path[0].y+(path[1].y-path[0].y)*t};return{segments:[{kind:'line3',start:{...path[0],z:zStart},end:{...end,z:zEnd},feedMmMin:operation.plungeMmMin}]};}const center=centroid(path),r=Math.max(.25,Math.min(operation.tool.diameterMm*.35,distanceToBoundary(center,path)*.5));if(!(r>EPS))return{error:'Für die Taschenbahn passt kein sicherer Helix-Einstieg.'};const start={x:center.x+r,y:center.y};return{segments:[{kind:'arc3',start:{...start,z:zStart},end:{...start,z:zEnd},center,ccw:true,feedMmMin:operation.plungeMmMin}]};}

export function buildRegionPocketToolpath(args:{outer:P2[];islands?:P2[][];operation:PocketOperation;targetDepthMm:number;strategy:RegionPocketStrategy}):RegionPocketResult{
  const {operation,targetDepthMm,strategy}=args,errors:string[]=[],warnings:string[]=[];if(!(operation.tool.diameterMm>0&&operation.stepoverPercent>0&&operation.stepoverPercent<=100&&operation.stepDownMm>0&&targetDepthMm>0))return{toolpath:null,errors:['Taschenstrategie benötigt gültiges Werkzeug, Stepover, Zustellung und Zieltiefe.'],warnings};
  const toolRadius=operation.tool.diameterMm/2,outer=chooseOffset(args.outer,toolRadius,false),islands=(args.islands??[]).map(loop=>chooseOffset(loop,toolRadius,true));if(areaAbs(outer)<=EPS)return{toolpath:null,errors:['Werkzeug ist für die Taschenregion zu groß.'],warnings};
  const stepover=Math.max(.05,operation.tool.diameterMm*operation.stepoverPercent/100);const planned=strategy==='parallel'?{paths:parallelPaths(outer,islands,stepover),error:null as string|null}:concentricPaths(outer,islands,stepover);if(planned.error)errors.push(planned.error);if(!planned.paths.length)errors.push(`Für ${strategy==='concentric'?'Kreis':'Konturparallel'} konnte keine sichere Taschenbahn erzeugt werden.`);if(errors.length)return{toolpath:null,errors,warnings};
  const passes=Math.max(1,Math.ceil(targetDepthMm/operation.stepDownMm)),runs:CanonicalToolpath['runs']=[];for(let pass=1;pass<=passes;pass++){const z=-Math.min(targetDepthMm,pass*operation.stepDownMm),zStart=pass===1?0:-Math.min(targetDepthMm,(pass-1)*operation.stepDownMm);for(const path of planned.paths){const entry=entryForPath(operation,path,zStart,z);if(entry.error){errors.push(entry.error);break;}runs.push({kind:'cut',z,points:path,segments:lineSegments(path),entrySegments:entry.segments,retractAfter:true});}if(errors.length)break;}
  if(errors.length)return{toolpath:null,errors,warnings};warnings.push(strategy==='concentric'?'Kreisräumen verwendet konzentrische Kernbahnen plus konturparallele Cleanup-Schalen für Ecken und Freiformbereiche.':'Konturparallel verwendet werkzeugradiuskorrigierte Offset-Schalen der Sollkontur.');return{toolpath:{version:1,operationKind:'pocket',strategy:strategy==='parallel'?'parallel-pocket':'concentric',tool:{diameterMm:operation.tool.diameterMm},stepoverPercent:operation.stepoverPercent,runs},errors:[],warnings};
}
