import type { MillingToolKind } from './toolTypes';

export type ImportKind = 'step' | 'dxf';
export interface Point2 { x:number;y:number; } export interface Bounds2 { min:Point2;max:Point2; }
export type Curve2=|{kind:'line';start:Point2;end:Point2}|{kind:'circle';center:Point2;radius:number}|{kind:'arc';center:Point2;radius:number;startAngleDeg:number;endAngleDeg:number}|{kind:'polyline';points:Point2[];bulges?:number[];closed:boolean}|{kind:'unsupported';sourceKind:string};
export interface PlanarGeometry { curves:Curve2[];curveLayers?:string[];layerNames?:string[];bounds?:Bounds2; }
export interface SurfaceTypeSummary {kind:string;count:number;} export interface BrepSummary {backend:string;nativeBrep:boolean;faces:number;edges:number;vertices:number;solids:number;surfaceTypes:SurfaceTypeSummary[];cylinderRadiiMm:number[];displayTriangles:number;displayVertices:number[];note:string;} export interface ImportSummary {kind:ImportKind;fileName:string;backend:string;status:'ready'|'native-adapter-pending';entities:Record<string,number>;planarGeometry?:PlanarGeometry;brep?:BrepSummary;note?:string;}
export type StockMode='manual'|'part-bounds'|'none';export interface StockDefinition{width:number;height:number;thickness:number;offsetX:number;offsetY:number;offsetZ:number;} export type HorizontalPlacement='left'|'center'|'right';export type VerticalPlacement='front'|'center'|'back';export interface PartPlacement{horizontal:HorizontalPlacement;vertical:VerticalPlacement;offsetX:number;offsetY:number;offsetZ:number;}export interface PartOrientation{rotationXDeg:number;rotationYDeg:number;rotationZDeg:number;}export type WcsX='left'|'center'|'right';export type WcsY='front'|'center'|'back';export type WcsZ='top'|'bottom';export type WcsReference='stock'|'part';export interface WorkCoordinateSystem{x:WcsX;y:WcsY;z:WcsZ;}export interface SetupDefinition{id:string;name:string;stockMode:StockMode;orientation:PartOrientation;placement:PartPlacement;wcsReference:WcsReference;wcs:WorkCoordinateSystem;}
export type OperationKind='facing'|'contour'|'pocket'|'carve'|'drill';export type ToolpathSide='outside'|'inside'|'on-line';export type CutDirection='conventional'|'climb';export type PocketEntry='plunge'|'ramp';export type PocketStrategy='auto'|'raster'|'concentric'|'parallel';export type CarveSelectionMode='individual'|'layer';export type DrillSelectionMode='individual'|'layer';export type DrillMethod='drill'|'helical-mill';export type FacingDirection='x'|'y';export interface ToolDefinition{id:string;name:string;diameterMm:number;kind?:MillingToolKind;}
interface BaseOperation{id:string;name:string;enabled:boolean;tool:ToolDefinition;totalDepthMm:number;stepDownMm:number;feedMmMin:number;plungeMmMin:number;spindleRpm:number;safeZMm:number;}
export interface FacingOperation extends BaseOperation{kind:'facing';direction:FacingDirection;stepoverPercent:number;}
export interface ContourOperation extends BaseOperation{kind:'contour';contourId:number|null;side:ToolpathSide;direction:CutDirection;}
export interface PocketOperation extends BaseOperation{kind:'pocket';contourId:number|null;direction:CutDirection;stepoverPercent:number;entry:PocketEntry;rampAngleDeg:number;strategy:PocketStrategy;}
export interface CarveOperation extends BaseOperation{kind:'carve';curveIds:number[];layerName:string|null;selectionMode:CarveSelectionMode;}
export interface DrillOperation extends BaseOperation{kind:'drill';curveIds:number[];layerName:string|null;selectionMode:DrillSelectionMode;method:DrillMethod;}
export type CamOperation=FacingOperation|ContourOperation|PocketOperation|CarveOperation|DrillOperation;
export interface OperationsProject { operations:CamOperation[];activeOperationId:string|null; }
export const defaultStock:StockDefinition={width:200,height:80,thickness:22,offsetX:10,offsetY:10,offsetZ:0};export const defaultPartPlacement:PartPlacement={horizontal:'center',vertical:'center',offsetX:0,offsetY:0,offsetZ:0};export const defaultPartOrientation:PartOrientation={rotationXDeg:0,rotationYDeg:0,rotationZDeg:0};export const defaultWcs:WorkCoordinateSystem={x:'left',y:'front',z:'top'};export const defaultSetup:SetupDefinition={id:'setup-1',name:'Aufspannung 1',stockMode:'manual',orientation:{...defaultPartOrientation},placement:{...defaultPartPlacement},wcsReference:'stock',wcs:{...defaultWcs}};
export const defaultFacingOperation:FacingOperation={id:'op-facing-1',kind:'facing',name:'Planen 1',enabled:true,tool:{id:'tool-face-1',name:'Planfräser 20 mm',diameterMm:20,kind:'face-mill'},direction:'x',stepoverPercent:60,totalDepthMm:.5,stepDownMm:.5,feedMmMin:800,plungeMmMin:200,spindleRpm:12000,safeZMm:5};
export const defaultContourOperation:ContourOperation={id:'op-contour-1',kind:'contour',name:'Kontur 1',enabled:true,contourId:null,tool:{id:'tool-1',name:'Schaftfräser 3 mm',diameterMm:3,kind:'end-mill'},side:'outside',direction:'climb',totalDepthMm:3,stepDownMm:1,feedMmMin:600,plungeMmMin:200,spindleRpm:12000,safeZMm:5};
export const defaultPocketOperation:PocketOperation={id:'op-pocket-1',kind:'pocket',name:'Tasche 1',enabled:true,contourId:null,tool:{id:'tool-1',name:'Schaftfräser 3 mm',diameterMm:3,kind:'end-mill'},direction:'climb',totalDepthMm:3,stepDownMm:1,stepoverPercent:40,entry:'plunge',rampAngleDeg:3,strategy:'auto',feedMmMin:600,plungeMmMin:200,spindleRpm:12000,safeZMm:5};
export const defaultCarveOperation:CarveOperation={id:'op-carve-1',kind:'carve',name:'Carve 1',enabled:true,curveIds:[],layerName:null,selectionMode:'individual',tool:{id:'tool-carve-1',name:'Schaftfräser 0,6 mm',diameterMm:.6,kind:'end-mill'},totalDepthMm:1,stepDownMm:.5,feedMmMin:250,plungeMmMin:100,spindleRpm:16000,safeZMm:5};
export const defaultDrillOperation:DrillOperation={id:'op-drill-1',kind:'drill',name:'Bohren 1',enabled:true,curveIds:[],layerName:null,selectionMode:'individual',method:'drill',tool:{id:'tool-drill-1',name:'Bohrer 3 mm',diameterMm:3},totalDepthMm:5,stepDownMm:5,feedMmMin:180,plungeMmMin:120,spindleRpm:10000,safeZMm:5};
export const defaultOperationsProject:OperationsProject={operations:[{...defaultContourOperation,tool:{...defaultContourOperation.tool}}],activeOperationId:defaultContourOperation.id};
