import type { MillingToolKind } from './toolTypes';

export type ImportKind = 'step' | 'dxf';
export interface Point2 { x:number;y:number; } export interface Bounds2 { min:Point2;max:Point2; }
export type Curve2=|{kind:'line';start:Point2;end:Point2}|{kind:'circle';center:Point2;radius:number}|{kind:'arc';center:Point2;radius:number;startAngleDeg:number;endAngleDeg:number}|{kind:'polyline';points:Point2[];bulges?:number[];closed:boolean}|{kind:'unsupported';sourceKind:string};
export interface PlanarGeometry { curves:Curve2[];curveLayers?:string[];layerNames?:string[];bounds?:Bounds2; }
export interface SurfaceTypeSummary {kind:string;count:number;} export interface BrepSummary {backend:string;nativeBrep:boolean;faces:number;edges:number;vertices:number;solids:number;surfaceTypes:SurfaceTypeSummary[];cylinderRadiiMm:number[];displayTriangles:number;displayVertices:number[];displayFaceIds?:number[];displayEdges?:number[][];note:string;} export interface ImportSummary {kind:ImportKind;fileName:string;backend:string;status:'ready'|'native-adapter-pending';entities:Record<string,number>;planarGeometry?:PlanarGeometry;brep?:BrepSummary;note?:string;}
export type StockMode='manual'|'part-bounds'|'none';export interface StockDefinition{width:number;height:number;thickness:number;offsetX:number;offsetY:number;offsetZ:number;} export type HorizontalPlacement='left'|'center'|'right';export type VerticalPlacement='front'|'center'|'back';export interface PartPlacement{horizontal:HorizontalPlacement;vertical:VerticalPlacement;offsetX:number;offsetY:number;offsetZ:number;}export interface PartOrientation{rotationXDeg:number;rotationYDeg:number;rotationZDeg:number;}export type WcsX='left'|'center'|'right';export type WcsY='front'|'center'|'back';export type WcsZ='top'|'bottom';export type WcsReference='stock'|'part';export interface WorkCoordinateSystem{x:WcsX;y:WcsY;z:WcsZ;}export interface SetupDefinition{id:string;name:string;stockMode:StockMode;orientation:PartOrientation;placement:PartPlacement;wcsReference:WcsReference;wcs:WorkCoordinateSystem;}
export type OperationKind='facing'|'contour'|'pocket'|'carve'|'surface-carve'|'drill'|'z-level-roughing'|'surface-finishing';export type ToolpathSide='outside'|'inside'|'on-line';export type OpenContourSide='left'|'right'|'on-line';export type ContourTopology='closed'|'open';export type ContourDepthMode='manual'|'stock-bottom';export type DrillDepthMode='manual'|'stock-bottom';export type ContourLeadMode='none'|'line';export type CutDirection='conventional'|'climb';export type PocketEntry='plunge'|'ramp'|'helix';export type PocketStrategy='auto'|'raster'|'concentric'|'parallel';export type CarveSelectionMode='individual'|'layer';export type DrillSelectionMode='individual'|'layer';export type DrillMethod='drill'|'helical-mill';export type ZLevelRoughingMode='face-target'|'model';export type ZLevelIslandMode='preserve'|'clear';export type FacingDirection='x'|'y';export interface ToolDefinition{id:string;name:string;diameterMm:number;kind?:MillingToolKind;cuttingLengthMm?:number;stickoutMm?:number;shaftDiameterMm?:number;holderDiameterMm?:number;}
interface BaseOperation{id:string;name:string;enabled:boolean;tool:ToolDefinition;totalDepthMm:number;stepDownMm:number;feedMmMin:number;plungeMmMin:number;spindleRpm:number;safeZMm:number;}
export interface FacingOperation extends BaseOperation{kind:'facing';direction:FacingDirection;stepoverPercent:number;stockAllowanceMm?:number;finishPassCount?:number;}
export interface ContourOperation extends BaseOperation{kind:'contour';contourId:number|null;contourIds?:number[];stepWireId?:number|null;stepContourFaceIds?:number[];depthMode?:ContourDepthMode;overcutMm?:number;tabsEnabled?:boolean;tabCount?:number;tabWidthMm?:number;tabHeightMm?:number;leadMode?:ContourLeadMode;leadInLengthMm?:number;leadOutLengthMm?:number;radialAllowanceMm?:number;axialAllowanceMm?:number;finishPassEnabled?:boolean;finishPassCount?:number;topology:ContourTopology;side:ToolpathSide;openSide:OpenContourSide;excludedSegmentIds?:number[];direction:CutDirection;}
export interface PocketOperation extends BaseOperation{kind:'pocket';contourId:number|null;contourIds?:number[];stepFaceId?:number|null;restMachiningEnabled?:boolean;restFromOperationId?:string|null;stockAwareRoughingEnabled?:boolean;maxRadialEngagementPercent?:number;radialAllowanceMm?:number;axialAllowanceMm?:number;finishPassEnabled?:boolean;finishPassCount?:number;direction:CutDirection;stepoverPercent:number;entry:PocketEntry;rampAngleDeg:number;strategy:PocketStrategy;throughCutAllowanceMm?:number;}
export interface CarveOperation extends BaseOperation{kind:'carve';curveIds:number[];layerName:string|null;selectionMode:CarveSelectionMode;side:OpenContourSide;}
export interface SurfaceCarveGeometrySourceRef{id:string;path:string;fileName:string;offsetX:number;offsetY:number;scale:number;rotationDeg:number;}
export interface SurfaceCarveOperation extends BaseOperation{kind:'surface-carve';faceId:number|null;roughingOperationId:string|null;geometrySourceId:string|null;geometrySource:SurfaceCarveGeometrySourceRef|null;}
export interface DrillOperation extends BaseOperation{kind:'drill';curveIds:number[];stepHoleFeatureIds?:string[];layerName:string|null;selectionMode:DrillSelectionMode;method:DrillMethod;depthMode?:DrillDepthMode;overcutMm?:number;}
export interface SurfaceFinishingOperation extends BaseOperation{kind:'surface-finishing';faceIds:number[];stepoverPercent:number;direction:'x'|'y';}
export interface ZLevelRoughingOperation extends BaseOperation{kind:'z-level-roughing';faceIds:number[];roughingMode?:ZLevelRoughingMode;islandMode?:ZLevelIslandMode;stepoverPercent:number;finishAllowanceMm:number;}
export type CamOperation=FacingOperation|ContourOperation|PocketOperation|CarveOperation|SurfaceCarveOperation|DrillOperation|ZLevelRoughingOperation|SurfaceFinishingOperation;
export interface OperationsProject { operations:CamOperation[];activeOperationId:string|null; }
export const defaultStock:StockDefinition={width:200,height:80,thickness:22,offsetX:10,offsetY:10,offsetZ:0};export const defaultPartPlacement:PartPlacement={horizontal:'center',vertical:'center',offsetX:0,offsetY:0,offsetZ:0};export const defaultPartOrientation:PartOrientation={rotationXDeg:0,rotationYDeg:0,rotationZDeg:0};export const defaultWcs:WorkCoordinateSystem={x:'left',y:'front',z:'top'};export const defaultSetup:SetupDefinition={id:'setup-1',name:'Aufspannung 1',stockMode:'manual',orientation:{...defaultPartOrientation},placement:{...defaultPartPlacement},wcsReference:'stock',wcs:{...defaultWcs}};
export const defaultFacingOperation:FacingOperation={id:'op-facing-1',kind:'facing',name:'Planen 1',enabled:true,tool:{id:'tool-face-1',name:'Planfräser 20 mm',diameterMm:20,kind:'face-mill',cuttingLengthMm:5,stickoutMm:20,shaftDiameterMm:20,holderDiameterMm:25},direction:'x',stepoverPercent:60,stockAllowanceMm:0,finishPassCount:1,totalDepthMm:.5,stepDownMm:.5,feedMmMin:800,plungeMmMin:200,spindleRpm:12000,safeZMm:5};
export const defaultContourOperation:ContourOperation={id:'op-contour-1',kind:'contour',name:'Kontur 1',enabled:true,tool:{id:'tool-1',name:'Schaftfräser 3 mm',diameterMm:3,kind:'end-mill',cuttingLengthMm:12,stickoutMm:20,shaftDiameterMm:3,holderDiameterMm:20},contourId:null,contourIds:[],stepWireId:null,stepContourFaceIds:[],depthMode:'manual',overcutMm:0,tabsEnabled:false,tabCount:4,tabWidthMm:6,tabHeightMm:1.5,leadMode:'none',leadInLengthMm:3,leadOutLengthMm:3,radialAllowanceMm:0,axialAllowanceMm:0,finishPassEnabled:false,finishPassCount:1,topology:'closed',side:'outside',openSide:'left',excludedSegmentIds:[],direction:'climb',totalDepthMm:3,stepDownMm:1,feedMmMin:600,plungeMmMin:200,spindleRpm:12000,safeZMm:5};
export const defaultPocketOperation:PocketOperation={id:'op-pocket-1',kind:'pocket',name:'Tasche 1',enabled:true,contourId:null,contourIds:[],stepFaceId:null,restMachiningEnabled:false,restFromOperationId:null,stockAwareRoughingEnabled:false,maxRadialEngagementPercent:35,radialAllowanceMm:0,axialAllowanceMm:0,finishPassEnabled:false,finishPassCount:1,tool:{id:'tool-1',name:'Schaftfräser 3 mm',diameterMm:3,kind:'end-mill',cuttingLengthMm:12,stickoutMm:20,shaftDiameterMm:3,holderDiameterMm:20},direction:'climb',stepoverPercent:40,entry:'plunge',rampAngleDeg:3,strategy:'auto',throughCutAllowanceMm:0,totalDepthMm:3,stepDownMm:1,feedMmMin:600,plungeMmMin:200,spindleRpm:12000,safeZMm:5};
export const defaultCarveOperation:CarveOperation={id:'op-carve-1',kind:'carve',name:'Carve 1',enabled:true,curveIds:[],layerName:null,selectionMode:'individual',side:'on-line',tool:{id:'tool-carve-1',name:'Schaftfräser 0,6 mm',diameterMm:.6,kind:'end-mill',cuttingLengthMm:4,stickoutMm:15,shaftDiameterMm:3,holderDiameterMm:20},totalDepthMm:1,stepDownMm:.5,feedMmMin:250,plungeMmMin:100,spindleRpm:16000,safeZMm:5};
export const defaultSurfaceCarveOperation:SurfaceCarveOperation={id:'op-surface-carve-1',kind:'surface-carve',name:'Surface Carve 1',enabled:true,faceId:null,roughingOperationId:null,geometrySourceId:null,geometrySource:null,tool:{id:'tool-surface-carve-1',name:'Schaftfräser 0,6 mm',diameterMm:.6,kind:'end-mill',cuttingLengthMm:4,stickoutMm:15,shaftDiameterMm:3,holderDiameterMm:20},totalDepthMm:.5,stepDownMm:.5,feedMmMin:250,plungeMmMin:100,spindleRpm:16000,safeZMm:5};
export const defaultDrillOperation:DrillOperation={id:'op-drill-1',kind:'drill',name:'Bohren 1',enabled:true,curveIds:[],stepHoleFeatureIds:[],layerName:null,selectionMode:'individual',method:'drill',depthMode:'manual',overcutMm:1,tool:{id:'tool-drill-1',name:'Bohrer 3 mm',diameterMm:3,cuttingLengthMm:20,stickoutMm:25,shaftDiameterMm:3,holderDiameterMm:20},totalDepthMm:5,stepDownMm:5,feedMmMin:180,plungeMmMin:120,spindleRpm:10000,safeZMm:5};
export const defaultSurfaceFinishingOperation:SurfaceFinishingOperation={id:'op-surface-finishing-1',kind:'surface-finishing',name:'3D Schlichten 1',enabled:true,faceIds:[],tool:{id:'tool-finish-1',name:'Vollradiusfräser 3 mm',diameterMm:3,kind:'ball-nose',cuttingLengthMm:12,stickoutMm:25,shaftDiameterMm:3,holderDiameterMm:20},stepoverPercent:12,direction:'x',totalDepthMm:0,stepDownMm:1,feedMmMin:500,plungeMmMin:150,spindleRpm:14000,safeZMm:5};
export const defaultZLevelRoughingOperation:ZLevelRoughingOperation={id:'op-z-level-roughing-1',kind:'z-level-roughing',name:'Z-Level Schruppen 1',enabled:true,faceIds:[],roughingMode:'face-target',islandMode:'preserve',tool:{id:'tool-roughing-1',name:'Schaftfräser 6 mm',diameterMm:6,kind:'end-mill',cuttingLengthMm:15,stickoutMm:25,shaftDiameterMm:6,holderDiameterMm:20},stepoverPercent:40,finishAllowanceMm:.5,totalDepthMm:0,stepDownMm:2,feedMmMin:600,plungeMmMin:200,spindleRpm:12000,safeZMm:5};
export const defaultOperationsProject:OperationsProject={operations:[{...defaultContourOperation,tool:{...defaultContourOperation.tool}}],activeOperationId:defaultContourOperation.id};