import { buildTrochoidalContourOperationState } from '../../src/lib/trochoidalOperationState';
import { buildActiveCanonicalToolpath } from '../../src/lib/activeCanonicalToolpath';
import { validateJob } from '../../src/lib/jobPreflight';
import { createOperation } from '../../src/lib/operationsProject';
import type { ImportSummary, StockDefinition, PartPlacement, PartOrientation, WorkCoordinateSystem } from '../../src/lib/types';
const expect=(ok:boolean,message:string)=>{if(!ok)throw new Error(message);};
const summary:ImportSummary={kind:'dxf',fileName:'f7.dxf',backend:'acceptance',status:'ready',entities:{circle:1},planarGeometry:{curves:[{kind:'circle',center:{x:10,y:10},radius:20}]}};
const stock:StockDefinition={width:80,height:60,thickness:12,offsetX:0,offsetY:0,offsetZ:0};
const placement:PartPlacement={horizontal:'center',vertical:'center',offsetX:3,offsetY:-2,offsetZ:0};
const orientation:PartOrientation={rotationXDeg:0,rotationYDeg:0,rotationZDeg:23};
const wcs:WorkCoordinateSystem={x:'left',y:'front',z:'top'};
const operation=createOperation('trochoidal-contour-roughing',1);
if(operation.kind!=='trochoidal-contour-roughing')throw new Error('operation kind');
operation.contourId=0;operation.totalDepthMm=2.4;operation.stepDownMm=1;operation.trochoidRadiusMm=4;operation.forwardStepMm=.5;
const before=JSON.stringify({summary,stock,placement,orientation,wcs,operation});
const state=buildTrochoidalContourOperationState({summary,stock,stockMode:'manual',placement,orientation,wcs,operation});
expect(state.ok,'F7 operation state: '+state.errors.join(' '));
if(state.ok){expect(state.toolpath.sourceOperationId===operation.id,'stable source operation id');expect(JSON.stringify(state.toolpath.runs.map(r=>r.z))===JSON.stringify([-1,-2,-2.4]),'F6 depth schedule retained');expect(!!state.toolpath.motions?.length,'F6 motion authority retained');}
const active=buildActiveCanonicalToolpath({summary,stock,stockMode:'manual',placement,orientation,wcs,operation});
expect(!!active&&active.sourceOperationId===operation.id,'active canonical route uses F7');
expect(JSON.stringify(active)===JSON.stringify(state.ok?state.toolpath:null),'active route equals direct F7 state');
const job=validateJob({summary,stock,stockMode:'manual',placement,orientation,wcs,operations:[operation]});
expect(job.level!=='fail','job preflight: '+job.errors.join(' '));
expect(job.operations.length===1&&job.operations[0].kind==='trochoidal-contour-roughing','job operation retained');
expect(!!job.operations[0].toolpath?.motions?.length,'004T materializes complete motion chain');
expect(job.operations[0].toolpath?.sourceOperationId===operation.id,'004T preserves source identity');
expect(JSON.stringify({summary,stock,placement,orientation,wcs,operation})===before,'inputs immutable');
const step={...summary,kind:'step' as const,planarGeometry:undefined};
const rejectedStep=buildTrochoidalContourOperationState({summary:step,stock,stockMode:'manual',placement,orientation,wcs,operation});expect(!rejectedStep.ok&&rejectedStep.toolpath===null,'STEP fails closed');
const rejectedWcs=buildTrochoidalContourOperationState({summary,stock,stockMode:'manual',placement,orientation,wcs:{...wcs,z:'bottom'},operation});expect(!rejectedWcs.ok&&rejectedWcs.toolpath===null,'bottom WCS fails closed');
const rejectedOperation=buildTrochoidalContourOperationState({summary,stock,stockMode:'manual',placement,orientation,wcs,operation:{...operation,id:'',contourId:null}});expect(!rejectedOperation.ok&&rejectedOperation.toolpath===null,'invalid operation fails closed');
console.log('010-F7 trochoid operation/job integration: PASS');
