import { validateJob } from '../../src/lib/jobPreflight';
import { generateJobGcode } from '../../src/lib/jobGcode';
import { createOperation } from '../../src/lib/operationsProject';
import { postCanonicalMachineMotions } from '../../src/lib/canonicalMotionGcode';
import type { ImportSummary, StockDefinition, PartPlacement, PartOrientation, WorkCoordinateSystem } from '../../src/lib/types';
const expect=(ok:boolean,message:string)=>{if(!ok)throw new Error(message);};
const summary:ImportSummary={kind:'dxf',fileName:'f13.dxf',backend:'acceptance',status:'ready',entities:{circle:1},planarGeometry:{curves:[{kind:'circle',center:{x:20,y:20},radius:12}]}};
const stock:StockDefinition={width:60,height:60,thickness:6,offsetX:0,offsetY:0,offsetZ:0};
const placement:PartPlacement={horizontal:'center',vertical:'center',offsetX:0,offsetY:0,offsetZ:0};
const orientation:PartOrientation={rotationXDeg:0,rotationYDeg:0,rotationZDeg:0};
const wcs:WorkCoordinateSystem={x:'left',y:'front',z:'top'};
const operation=createOperation('trochoidal-contour-roughing',1);
if(operation.kind!=='trochoidal-contour-roughing')throw new Error('operation kind');
operation.contourId=0;operation.side='outside';operation.direction='climb';operation.depthMode='stock-bottom';operation.totalDepthMm=6;operation.overcutMm=.3;operation.stepDownMm=2.5;operation.safeZMm=5;operation.trochoidRadiusMm=2;operation.forwardStepMm=.6;operation.rampAngleDeg=3;operation.feedMmMin=500;operation.plungeMmMin=180;operation.spindleRpm=9000;
operation.tool.cuttingLengthMm=12;
const args={summary,stock,stockMode:'manual' as const,placement,orientation,wcs,operations:[operation],spoilboardThicknessMm:.5};
const preflight=validateJob(args);
expect(preflight.level!=='fail','F13 preflight: '+preflight.errors.join(' '));
const toolpath=preflight.operations[0]?.toolpath;
expect(!!toolpath?.motions?.length,'F13 requires materialized canonical motions');
expect(toolpath?.sourceOperationId===operation.id,'source operation identity retained into NC authority');
const motions=toolpath!.motions!;
expect(motions[0].kind==='rapid3'&&Math.abs(motions[0].start.z-operation.safeZMm)<1e-9,'first canonical motion starts at Safe-Z');
expect(motions.some(m=>m.kind==='rapid3'),'canonical chain contains rapid safety moves');
expect(motions.some(m=>m.kind==='line3'&&Math.abs(m.start.z-m.end.z)>1e-9),'canonical chain contains spatial pendulum ramp moves');
expect(motions.some(m=>m.kind==='arc3'),'canonical chain contains trochoidal arcs');
const rampMotions=motions.filter(m=>m.kind!=='rapid3'&&Math.abs(m.start.z-m.end.z)>1e-9);
const planarCutMotions=motions.filter(m=>m.kind!=='rapid3'&&Math.abs(m.start.z-m.end.z)<=1e-9);
expect(rampMotions.length>0&&rampMotions.every(m=>(m.feedMmMin??operation.plungeMmMin)===operation.plungeMmMin),'all spatial ramp motions retain plunge/ramp feed');
expect(planarCutMotions.length>0&&planarCutMotions.every(m=>(m.feedMmMin??operation.feedMmMin)===operation.feedMmMin),'all planar cutting motions retain cutting feed');
const minZ=Math.min(...motions.flatMap(m=>[m.start.z,m.end.z]));
expect(Math.abs(minZ+6.3)<1e-9,'stock-bottom plus overcut reaches exactly Z-6.300');
const result=generateJobGcode({...args,preflight});
expect(result.ok,'F13 NC release: '+result.errors.join(' '));
expect(result.operationCount===1&&result.toolChangeCount===0,'single trochoid job metadata');
expect(result.code.includes('( BeBlog CAM 004T )'),'NC declares canonical 004T authority');
expect(result.code.includes('M3 S9000'),'spindle command retained');
expect(result.code.includes('G0 '),'NC contains rapid safety moves');
expect(result.code.includes('G1 '),'NC contains linear feed/ramp moves');
expect(result.code.includes('F180.000'),'NC retains ramp/plunge feed');
expect(result.code.includes('F500.000'),'NC retains planar cutting feed');
expect(result.code.includes('G2 ')||result.code.includes('G3 '),'NC contains canonical arcs');
expect(result.code.includes('Z-6.300'),'NC contains exact overcut depth');
expect(result.code.trimEnd().endsWith('M30'),'NC terminates with M30');
const posted=postCanonicalMachineMotions({motions,operation});
const lines=result.code.split(/\r?\n/);
let cursor=-1;
for(const line of posted){const next=lines.indexOf(line,cursor+1);expect(next>cursor,'canonical motion missing or reordered in NC: '+line);cursor=next;}
expect(posted.length===motions.length,'one NC motion line per canonical motion');
console.log('010-F13 trochoidal canonical NC release: PASS');
