import { validateJob } from '../../src/lib/jobPreflight';
import { validateTrochoidalSpoilboardClearance } from '../../src/lib/trochoidalSpoilboardClearance';
import { createOperation } from '../../src/lib/operationsProject';
import { createCamProjectV1, parseCamProject, serializeCamProject } from '../../src/lib/projectPersistence';
import type { ImportSummary,StockDefinition,PartPlacement,PartOrientation,WorkCoordinateSystem } from '../../src/lib/types';
const expect=(ok:boolean,msg:string)=>{if(!ok)throw new Error(msg)};
const summary:ImportSummary={kind:'dxf',fileName:'f9.dxf',backend:'acceptance',status:'ready',entities:{circle:1},planarGeometry:{curves:[{kind:'circle',center:{x:10,y:10},radius:20}]}};
const stock:StockDefinition={width:80,height:60,thickness:12,offsetX:0,offsetY:0,offsetZ:0};
const placement:PartPlacement={horizontal:'center',vertical:'center',offsetX:0,offsetY:0,offsetZ:0};
const orientation:PartOrientation={rotationXDeg:0,rotationYDeg:0,rotationZDeg:0};
const wcs:WorkCoordinateSystem={x:'left',y:'front',z:'top'};
const op=createOperation('trochoidal-contour-roughing',1);if(op.kind!=='trochoidal-contour-roughing')throw new Error('kind');
op.contourId=0;op.depthMode='stock-bottom';op.overcutMm=.3;op.stepDownMm=5;op.tool.cuttingLengthMm=15;op.forwardStepMm=.5;
const direct=validateTrochoidalSpoilboardClearance(op,.5);
expect(direct.ok&&direct.requiredMm===.3&&direct.availableMm===.5&&Math.abs(direct.remainingMm-.2)<1e-9,'overcut consumes only spoilboard reserve');
const noBoard=validateJob({summary,stock,stockMode:'manual',placement,orientation,wcs,operations:[op]});
expect(noBoard.level==='fail'&&noBoard.operations[0].toolpath===null&&noBoard.operations[0].errors.some(e=>e.includes('Opferplatte')),'overcut without spoilboard fails closed in job preflight');
const tooThin=validateJob({summary,stock,stockMode:'manual',placement,orientation,wcs,operations:[op],spoilboardThicknessMm:.2});
expect(tooThin.level==='fail'&&tooThin.operations[0].toolpath===null,'overcut beyond spoilboard fails closed');
const project=createCamProjectV1({sourcePath:'/tmp/f9.dxf',sourceFileName:'f9.dxf',stock,stockMode:'manual',spoilboardThicknessMm:.5,placement,orientation,wcs,fixtures:[],machineEnvelopeEnabled:false,machineEnvelope:{minX:0,maxX:500,minY:0,maxY:500,minZ:-100,maxZ:0,warningMarginMm:5},machineWcsOrigin:{x:0,y:0,z:0},spindleHeadEnabled:false,spindleHead:{spindleNoseDiameterMm:80,spindleNoseBottomOffsetMm:60,spindleNoseLengthMm:80,carriageEnabled:false,carriageWidthMm:120,carriageDepthMm:120,carriageBottomOffsetMm:140,carriageHeightMm:120},operationsProject:{operations:[op],activeOperationId:op.id}});
const restored=parseCamProject(serializeCamProject(project));
expect(restored.setup.spoilboardThicknessMm===.5&&restored.operationsProject.operations[0].kind==='trochoidal-contour-roughing','spoilboard and trochoid survive project roundtrip');
const accepted=validateJob({summary,stock:restored.setup.stock,stockMode:restored.setup.stockMode,placement:restored.setup.placement,orientation:restored.setup.orientation,wcs:restored.setup.wcs,operations:restored.operationsProject.operations,spoilboardThicknessMm:restored.setup.spoilboardThicknessMm});
expect(accepted.level!=='fail'&&accepted.operations[0].toolpath!==null,'persisted setup spoilboard releases canonical job path');
const manual={...op,depthMode:'manual' as const,overcutMm:0,totalDepthMm:3};
const manualJob=validateJob({summary,stock,stockMode:'manual',placement,orientation,wcs,operations:[manual]});
expect(manualJob.level!=='fail','manual cut without overcut does not require spoilboard');
console.log('010-F9 spoilboard clearance: PASS');
